"""Operator-only dashboard helpers for the hosted M365 beta.

The dashboard session is a short-lived HMAC token derived from the configured
admin key.  The raw key is never placed in a cookie or returned to the client.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import os
import secrets
import time

from fastapi import Request

DASHBOARD_COOKIE = "codex_auth_m365_beta_dashboard"
DASHBOARD_SESSION_TTL = 8 * 60 * 60


def _b64url(value: bytes) -> str:
    return base64.urlsafe_b64encode(value).decode().rstrip("=")


def _session_secret() -> bytes:
    value = (
        os.environ.get("CODEX_AUTH_M365_BETA_DASHBOARD_SESSION_KEY")
        or os.environ.get("CODEX_AUTH_M365_BETA_ADMIN_KEY")
        or os.environ.get("CODEX_AUTH_M365_BETA_API_KEY")
        or ""
    )
    return value.encode()


def issue_dashboard_session(now: int | None = None) -> str:
    issued = int(now or time.time())
    payload = f"{issued}.{secrets.token_urlsafe(18)}"
    signature = hmac.new(_session_secret(), payload.encode(), hashlib.sha256).digest()
    return f"{payload}.{_b64url(signature)}"


def dashboard_session_valid(value: str, now: int | None = None) -> bool:
    if not value or not _session_secret():
        return False
    try:
        issued_raw, nonce, supplied = value.split(".", 2)
        issued = int(issued_raw)
    except (TypeError, ValueError):
        return False
    current = int(now or time.time())
    if issued > current + 60 or current - issued > DASHBOARD_SESSION_TTL:
        return False
    payload = f"{issued}.{nonce}"
    expected = _b64url(hmac.new(_session_secret(), payload.encode(), hashlib.sha256).digest())
    return secrets.compare_digest(supplied, expected)


def dashboard_request_authorized(request: Request) -> bool:
    return dashboard_session_valid(request.cookies.get(DASHBOARD_COOKIE, ""))


def dashboard_html_legacy() -> str:
    """Return the self-contained dashboard shell; all data loads after login."""

    return r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Codex Auth · M365 Beta</title><style>
:root{color-scheme:dark;--bg:#0b0d10;--panel:#12161b;--panel2:#171c22;--line:#2a313a;--text:#f4f7fa;--muted:#9ca7b3;--green:#29d69b;--amber:#ffbf47;--red:#ff6874;--blue:#67a9ff;--violet:#b69cff}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 75% 0,#18233a 0,transparent 32%),var(--bg);color:var(--text);font:14px/1.45 Inter,ui-sans-serif,system-ui,sans-serif}button,input,textarea{font:inherit}.hidden{display:none!important}
.login{min-height:100vh;display:grid;place-items:center;padding:24px}.login-card{width:min(430px,100%);padding:32px;border:1px solid var(--line);border-radius:20px;background:rgba(18,22,27,.94);box-shadow:0 28px 80px #0008}.brand{font-size:22px;font-weight:750}.brand span{font-weight:400;color:var(--muted)}
input,textarea{width:100%;border:1px solid var(--line);border-radius:10px;background:#0d1116;color:var(--text);padding:11px 12px;outline:none}input:focus,textarea:focus{border-color:var(--blue)}textarea{min-height:190px;resize:vertical}.btn{border:1px solid var(--line);border-radius:10px;background:#20262e;color:var(--text);padding:10px 14px;cursor:pointer}.btn:hover{border-color:#4a5665}.btn.primary{background:var(--text);color:#0b0d10;border-color:var(--text);font-weight:700}.btn.blue{background:#1768d5;border-color:#2f7ce3}.btn.danger{color:#ff9da5}.error{color:var(--red);min-height:20px}.muted{color:var(--muted)}
.app{min-height:100vh;display:grid;grid-template-columns:240px 1fr}.side{border-right:1px solid var(--line);padding:24px 16px;position:sticky;top:0;height:100vh;background:#0d1014}.nav{margin-top:32px;display:grid;gap:6px}.nav button{background:transparent;border:0;color:var(--muted);text-align:left;padding:11px 12px;border-radius:9px;cursor:pointer}.nav button.active,.nav button:hover{background:#20252c;color:var(--text)}.side-bottom{position:absolute;left:16px;right:16px;bottom:20px}
.main{padding:28px 34px 64px;max-width:1500px}.top{display:flex;align-items:center;justify-content:space-between;margin-bottom:26px}.title{font-size:25px;font-weight:760}.badge{display:inline-flex;align-items:center;gap:7px;padding:6px 10px;border:1px solid var(--line);border-radius:999px;color:var(--muted)}.dot{width:8px;height:8px;border-radius:50%;background:var(--amber)}.ok .dot{background:var(--green)}.bad .dot{background:var(--red)}
.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.card{border:1px solid var(--line);border-radius:15px;background:rgba(18,22,27,.88);padding:18px;min-width:0}.metric{font-size:25px;font-weight:760;margin-top:7px}.label{font-size:12px;letter-spacing:.08em;text-transform:uppercase;color:var(--muted)}.section{margin-top:22px}.section-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:12px}.section h2{margin:0;font-size:18px}.two{display:grid;grid-template-columns:1.15fr .85fr;gap:14px}.actions{display:flex;flex-wrap:wrap;gap:9px;margin-top:14px}.notice{border-left:3px solid var(--amber);background:#241c0d;padding:12px 14px;border-radius:8px;color:#ffd88a}.notice.blue{border-color:var(--blue);background:#111d30;color:#b7d6ff}.kv{display:grid;grid-template-columns:160px 1fr;gap:8px 14px;margin-top:14px}.kv div:nth-child(odd){color:var(--muted)}
table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:11px 10px;border-bottom:1px solid var(--line);vertical-align:top}th{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.06em}.state{font-size:12px;border:1px solid var(--line);padding:3px 7px;border-radius:999px;white-space:nowrap}.state.verified_live,.state.active{color:var(--green)}.state.blocked_by_upstream,.state.expiring_soon{color:var(--amber)}.state.unsupported,.state.re_import_required{color:var(--red)}
.logs{height:390px;overflow:auto;background:#090c0f;border:1px solid var(--line);border-radius:12px;padding:12px;font:12px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace;color:#b8c2cc}.log{padding:5px 0;border-bottom:1px solid #171c22}.view{display:none}.view.active{display:block}.split{display:grid;grid-template-columns:1fr 1fr;gap:14px}.file{position:relative;overflow:hidden}.file input{position:absolute;inset:0;opacity:0;cursor:pointer}
@media(max-width:1000px){.grid{grid-template-columns:repeat(2,1fr)}.two,.split{grid-template-columns:1fr}}@media(max-width:720px){.app{grid-template-columns:1fr}.side{height:auto;position:static;border-right:0;border-bottom:1px solid var(--line)}.nav{grid-template-columns:repeat(3,1fr);margin-top:18px}.side-bottom{position:static;margin-top:14px}.main{padding:22px 16px}.grid{grid-template-columns:1fr 1fr}}
/* Final accessibility overrides for the explicit shell. */
.nav button.active{color:#fff;background:#1f1f1f}.nav button:focus-visible,.sidebar-toggle:focus-visible,.theme-toggle:focus-visible,.btn:focus-visible{outline:2px solid var(--blue);outline-offset:2px}.nav button,.sidebar-toggle,.theme-toggle,.btn{min-height:44px}
@media(max-width:720px){.account-actions{display:grid}.account-actions .btn,.account-actions .file{width:100%;text-align:center}.account-recovery summary{cursor:pointer;padding:12px 0;font-weight:600}.account-recovery textarea{min-height:150px}}
</style></head><body>
<section id="login" class="login"><div class="login-card"><div class="brand">codex<span>-auth</span></div><h1>M365 Beta Dashboard</h1><p class="muted">Operator access uses the beta admin key. The key is exchanged for a short-lived HttpOnly session and is never stored in browser storage.</p><input id="loginKey" type="password" autocomplete="current-password" placeholder="Admin key"><div class="actions"><button class="btn primary" id="loginButton">Sign in</button></div><p id="loginError" class="error"></p></div></section>
<section id="app" class="app hidden"><aside class="side"><div class="brand">codex<span>-auth</span></div><div class="muted">M365 bearer beta</div><nav class="nav"><button data-view="overview" class="active">Overview</button><button data-view="account">Account</button><button data-view="models">Models</button><button data-view="capabilities">Capabilities</button><button data-view="verification">Verification</button><button data-view="logs">Live logs</button></nav><div class="side-bottom"><button id="logout" class="btn danger" style="width:100%">Sign out</button></div></aside>
<main class="main"><header class="top"><div><div id="pageTitle" class="title">Overview</div><div id="build" class="muted"></div></div><div id="connectionBadge" class="badge"><span class="dot"></span><span>Loading</span></div></header>
<div id="overview" class="view active"><div class="grid"><div class="card"><div class="label">Generation</div><div id="generation" class="metric">—</div></div><div class="card"><div class="label">Credential</div><div id="credentialState" class="metric">—</div></div><div class="card"><div class="label">Models</div><div id="modelCount" class="metric">—</div></div><div class="card"><div class="label">Persistence</div><div id="persistence" class="metric">—</div></div></div><section class="section two"><div class="card"><h2>Runtime</h2><div id="runtimeKv" class="kv"></div><div class="actions"><button class="btn blue" id="probe">Run safe connection test</button><button class="btn" id="refresh">Refresh credential</button></div><p id="actionStatus" class="muted"></p></div><div class="card"><h2>Deployment readiness</h2><div id="readiness"></div></div></section></div>
<div id="account" class="view"><section class="section two"><div class="card"><h2>Connect Microsoft 365</h2><p class="notice blue">Microsoft's M365 first-party clients reject device-code login and redirect browser authorization to Microsoft’s own landing page. This dashboard can open that sign-in, but browser isolation prevents Render from reading its token response automatically.</p><div class="actions"><button class="btn blue" id="openMicrosoft">Open Microsoft 365 sign-in</button></div><ol class="muted"><li>Sign in to Microsoft 365 in the opened tab.</li><li>Copy the successful OAuth token response JSON from DevTools.</li><li>Paste it below or select the JSON file. Route and refresh metadata are derived and preserved server-side.</li></ol><textarea id="credentialJson" spellcheck="false" autocomplete="off" placeholder='{"token_type":"Bearer", ...}'></textarea><div class="actions"><label class="btn file">Choose JSON file<input id="credentialFile" type="file" accept="application/json,.json"></label><button class="btn primary" id="importCredential">Import / Replace</button></div><p id="importStatus" class="muted"></p></div><div class="card"><h2>Credential health</h2><div id="credentialKv" class="kv"></div><p class="notice">Runtime imports survive restart only when encrypted external Postgres is configured. The dashboard never returns access or refresh tokens.</p></div></section></div>
<div id="models" class="view"><section class="section card"><div class="section-head"><h2>Available models</h2><span class="muted">Catalog source is shown per model</span></div><div style="overflow:auto"><table><thead><tr><th>Model</th><th>Name</th><th>Source</th><th>Reasoning</th></tr></thead><tbody id="modelsBody"></tbody></table></div></section></div>
<div id="capabilities" class="view"><section class="section card"><div class="section-head"><h2>Capability evidence</h2><span class="muted">No mock-only promotion</span></div><div style="overflow:auto"><table><thead><tr><th>Feature</th><th>State</th><th>Comparison</th><th>Evidence</th></tr></thead><tbody id="capabilitiesBody"></tbody></table></div></section></div>
<div id="verification" class="view"><section class="section split"><div class="card"><h2>Commit-bound verification</h2><div id="verificationKv" class="kv"></div></div><div class="card"><h2>Metrics</h2><div id="metricsKv" class="kv"></div></div></section></div>
<div id="logs" class="view"><section class="section"><div class="section-head"><h2>Redacted runtime events</h2><span class="muted">Prompts, responses, tokens, URLs, and identities are excluded</span></div><div id="logBox" class="logs"></div></section></div>
</main></section>
<script>
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let state=null,events=null;
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});let data={};try{data=await response.json()}catch{}if(response.status===401){showLogin();throw new Error('Dashboard session expired')}if(!response.ok)throw new Error(data.error||data.detail||'Request failed');return data}
function showLogin(){$('app').classList.add('hidden');$('login').classList.remove('hidden');if(events){events.close();events=null}}
function showApp(){$('login').classList.add('hidden');$('app').classList.remove('hidden')}
function kv(target,items){target.innerHTML=Object.entries(items).map(([k,v])=>`<div>${esc(k.replaceAll('_',' '))}</div><div>${esc(v??'Unavailable')}</div>`).join('')}
function badge(ok,text){$('connectionBadge').className='badge '+(ok?'ok':'bad');$('connectionBadge').innerHTML=`<span class="dot"></span><span>${esc(text)}</span>`}
async function load(){state=await api('/dashboard/api/overview');showApp();const c=state.credential||{},p=c.credential_persistence||{},models=state.models?.data||[],ready=state.readiness||{};$('generation').textContent=c.generation_ready?'Ready':'Blocked';$('credentialState').textContent=c.state||'Unknown';$('modelCount').textContent=models.length;$('persistence').textContent=p.restart_durable?'Durable':'Ephemeral';$('build').textContent=`Commit ${state.build?.render_commit||'unknown'} · contract ${state.build?.verification_contract||'unknown'}`;badge(c.generation_ready,c.generation_ready?'Connected':'Action required');kv($('runtimeKv'),{cookie_count:c.cookie_count,generation_ready:c.generation_ready,refresh_ready:c.refresh_ready,last_refresh_outcome:c.last_refresh_outcome,recovery_action:c.recovery_action});$('readiness').innerHTML=`<p class="${ready.ready?'':'notice'}">${ready.ready?'Ready for hosted generation':esc((ready.warnings||[]).join(' · ')||'Not ready')}</p>`;kv($('credentialKv'),{state:c.state,access_expires_in_seconds:c.access_expires_in_seconds,refresh_available:c.refresh_available,refresh_capture_state:c.refresh_capture_state,persistence_source:p.source,restart_durable:p.restart_durable});$('modelsBody').innerHTML=models.map(m=>`<tr><td>${esc(m.id)}</td><td>${esc(m.display_name||m.name||m.id)}</td><td>${esc(m.source||state.models?.source||'unknown')}</td><td>${esc(m.reasoning||m.metadata?.reasoning||'provider-defined')}</td></tr>`).join('')||'<tr><td colspan="4">No models reported</td></tr>';const features=state.capabilities?.features||[];$('capabilitiesBody').innerHTML=features.map(f=>`<tr><td>${esc(f.feature)}</td><td><span class="state ${esc(f.state)}">${esc(f.state)}</span></td><td>${esc(f.comparison)}</td><td>${esc(f.evidence_id)}</td></tr>`).join('');const v=state.verification?.verification||{};kv($('verificationKv'),{state:v.state,tested_commit:v.tested_commit,digest:v.digest,completed_at:v.completed_at?new Date(v.completed_at*1000).toLocaleString():null});const m=state.metrics||{};kv($('metricsKv'),{events:m.event_count,completed_generations:m.completed_generations,success_rate:m.success_rate,p50_ms:m.latency_ms?.p50,p95_ms:m.latency_ms?.p95,last_event_at:m.last_event_at?new Date(m.last_event_at*1000).toLocaleString():null});startLogs()}
function startLogs(){if(events)events.close();events=new EventSource('/dashboard/api/logs/stream');events.addEventListener('telemetry',event=>{let item={};try{item=JSON.parse(event.data)}catch{};const row=document.createElement('div');row.className='log';row.textContent=`${new Date((item.timestamp||0)*1000).toLocaleTimeString()}  ${item.event||'event'}  ${item.status||''}  ${item.model||''}  ${item.error_phase||''}`;$('logBox').appendChild(row);$('logBox').scrollTop=$('logBox').scrollHeight;while($('logBox').children.length>200)$('logBox').firstChild.remove()})}
$('loginButton').onclick=async()=>{const key=$('loginKey').value;$('loginError').textContent='';try{await api('/dashboard/login',{method:'POST',body:JSON.stringify({admin_key:key})});$('loginKey').value='';await load()}catch(error){$('loginKey').value='';$('loginError').textContent=error.message}};
$('logout').onclick=async()=>{await api('/dashboard/logout',{method:'POST'}).catch(()=>{});showLogin()};
document.querySelectorAll('.nav button').forEach(button=>button.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===button.dataset.view));$('pageTitle').textContent=button.textContent});
$('openMicrosoft').onclick=()=>window.open('https://m365.cloud.microsoft/chat?auth=2','_blank','noopener,noreferrer');
$('credentialFile').onchange=async event=>{const file=event.target.files[0];if(file)$('credentialJson').value=await file.text();event.target.value=''};
$('importCredential').onclick=async()=>{let credential;try{credential=JSON.parse($('credentialJson').value)}catch{$('importStatus').textContent='Select or paste a valid OAuth JSON object.';return}$('importStatus').textContent='Importing…';try{const result=await api('/dashboard/api/credentials/import',{method:'POST',body:JSON.stringify({credential})});$('importStatus').textContent=`Imported: ${result.credential.state}`;await load()}catch(error){$('importStatus').textContent=error.message}finally{$('credentialJson').value='';credential=null}};
$('refresh').onclick=async()=>{$('actionStatus').textContent='Refreshing…';try{const result=await api('/dashboard/api/refresh',{method:'POST'});$('actionStatus').textContent=`Refresh: ${result.credential.state}`;await load()}catch(error){$('actionStatus').textContent=error.message}};
$('probe').onclick=async()=>{$('actionStatus').textContent='Running zero-cookie marker probe…';try{const result=await api('/dashboard/api/probe',{method:'POST'});$('actionStatus').textContent=`${result.state}; ${result.latency_ms} ms; marker ${result.marker_observed?'verified':'missing'}`;await load()}catch(error){$('actionStatus').textContent=error.message}};
fetch('/dashboard/api/overview').then(r=>{if(r.ok)return load();showLogin()}).catch(showLogin);
</script></body></html>"""


def dashboard_html_injected_legacy() -> str:
    """Return the beta dashboard with the production console shell applied.

    The legacy shell is retained as the content source so this layout-only
    adaptation cannot accidentally change the beta API or credential flows.
    """

    html = dashboard_html_legacy()
    production_css = r"""
/* Production console skin: layout only; beta data and actions remain intact. */
:root{--prod-bg:#000;--prod-surface:#0a0a0a;--prod-hover:#171717;--prod-line:#27272a;--prod-strong:#3f3f46;--prod-text:#fff;--prod-muted:#a1a1aa;--prod-green:#10b981;--prod-blue:#3b82f6;--prod-sidebar:rgba(5,5,5,.86);--prod-blur:rgba(10,10,10,.82);--prod-width:240px}
:root.theme-light{color-scheme:light;--prod-bg:#fafafa;--prod-surface:#fff;--prod-hover:#f4f4f5;--prod-line:#e4e4e7;--prod-strong:#d4d4d8;--prod-text:#18181b;--prod-muted:#52525b;--prod-sidebar:rgba(255,255,255,.86);--prod-blur:rgba(255,255,255,.82)}
body{background:var(--prod-bg);background-image:radial-gradient(circle at center,rgba(127,127,127,.12) 1px,transparent 1px);background-size:24px 24px;color:var(--prod-text);min-height:100vh}
.login-card,.card{background:var(--prod-surface);border-color:var(--prod-strong);border-radius:12px}.login-card{box-shadow:0 28px 80px #0008}.brand-img{display:block;height:40px;width:auto;min-width:134px;content:url('/assets/logo-dark.svg')}.theme-light .brand-img{content:url('/assets/logo.svg')}
.app{grid-template-columns:var(--prod-width) minmax(0,1fr);transition:grid-template-columns .25s ease}.app.collapsed{--prod-width:72px}.side{padding:0;background:var(--prod-sidebar);border-right:1px solid var(--prod-line);backdrop-filter:blur(20px);display:flex;flex-direction:column;position:sticky;top:0;height:100vh}.side>.brand{height:80px;padding:20px 24px;border-bottom:1px solid var(--prod-line);width:100%;display:flex;align-items:center}.app.collapsed .side>.brand{width:72px;padding-left:18px;overflow:hidden}.side:before{content:'M365 bearer beta';order:2;color:var(--prod-muted);font-size:12px;padding:15px 24px 0}.nav{order:3;margin-top:10px;padding:0 12px;gap:6px}.nav button{border:0;background:transparent;color:var(--prod-muted);padding:10px 14px;border-radius:8px;display:flex;align-items:center;gap:10px;font-size:14px;cursor:pointer;text-align:left}.nav button:hover{background:rgba(127,127,127,.08);color:var(--prod-text)}.nav button.active{background:#1f1f1f;color:var(--prod-text);font-weight:600}.nav button svg{width:18px;height:18px;flex:0 0 18px}.app.collapsed .nav button{justify-content:center;padding:10px}.app.collapsed .nav button{font-size:0}.app.collapsed .nav button svg{margin:0}.side-bottom{order:4;position:static;margin-top:auto;padding:16px 12px}.app.collapsed .side-bottom .btn{font-size:0;padding:10px}.app.collapsed .side-bottom .btn:after{content:'↪';font-size:16px}
.main{padding:0;max-width:none;min-width:0;overflow:hidden}.top{height:72px;margin:0;padding:0 32px;border-bottom:1px solid var(--prod-line);background:var(--prod-blur);backdrop-filter:blur(10px);border-radius:0}.top:before{content:'Codex / ';color:var(--prod-muted);font-size:14px;margin-right:-24px}.title{font-size:14px;font-weight:500}.top>div:first-child{display:flex;align-items:baseline;gap:0}.top>div:first-child .muted{position:absolute;margin-top:25px;font-size:11px}.top .badge{margin-left:auto}.top:after{content:'☼';color:var(--prod-muted);font-size:20px;margin-left:18px;cursor:pointer}.view-container{padding:40px;overflow-y:auto;overflow-x:hidden;flex:1}.view{max-width:1500px;margin:0 auto}.view.active{display:block}.view>h1,.view>p{margin-left:0}
.header{margin-bottom:32px}.header h1{font-size:24px;font-weight:600;letter-spacing:-.03em}.header p{color:var(--prod-muted)}.grid{gap:16px}.card{padding:24px;transition:border-color .2s}.card:hover{border-color:var(--prod-muted)}.metric{font-size:31px;font-weight:600;letter-spacing:-.03em}.label{font-weight:500;color:var(--prod-muted)}.section{margin-top:0}.two,.split{gap:16px}.section-head{margin-bottom:16px}.section h2{font-size:18px;font-weight:600}.kv{margin-top:16px}.btn{border-radius:7px;background:var(--prod-surface);border-color:var(--prod-strong);padding:9px 13px}.btn:hover{background:var(--prod-hover);border-color:var(--prod-muted)}.btn.primary{background:var(--prod-text);color:var(--prod-bg);border-color:var(--prod-text)}.notice{border-radius:6px}.logs{height:420px;border-color:var(--prod-strong);border-radius:8px;background:var(--code)}table th{font-weight:500;padding:14px 16px;border-color:var(--prod-strong)}table td{padding:14px 16px;border-color:var(--prod-line)}table tr:hover td{background:var(--prod-hover)}
@media(max-width:1100px){.col-4{grid-column:span 6}}@media(max-width:800px){.col-4,.col-6,.col-8{grid-column:span 12}.two,.split{grid-template-columns:1fr}}@media(max-width:720px){.app{grid-template-columns:1fr}.side{height:auto;position:static;border-right:0;border-bottom:1px solid var(--prod-line)}.side>.brand{height:68px}.nav{grid-template-columns:repeat(3,1fr);padding:12px 10px;margin-top:0}.nav button{justify-content:center;padding:9px 5px;font-size:12px}.nav button svg{width:16px;height:16px}.side:before{display:none}.side-bottom{padding:0 10px 12px}.top{height:60px;padding:0 16px}.top:before{display:none}.top .badge{display:none}.view-container{padding:24px 16px}.grid{grid-template-columns:1fr 1fr}.card{padding:18px}}
"""
    html = html.replace('</style>', production_css + '</style>', 1)
    html = html.replace('<div class="brand">codex<span>-auth</span></div>', '<div class="brand"><img class="brand-img" src="/assets/logo-dark.svg" alt="Codex Auth"></div>')
    html = html.replace('<div class="brand">codex<span>-auth</span></div>', '<div class="brand"><img class="brand-img" src="/assets/logo-dark.svg" alt="Codex Auth"></div>')
    icons = {
        'Overview': '<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></svg>',
        'Account': '<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>',
        'Models': '<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m12 2 10 5-10 5L2 7l10-5Z"/><path d="m2 12 10 5 10-5M2 17l10 5 10-5"/></svg>',
        'Capabilities': '<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 3 4 7v5c0 5 3.5 8 8 9 4.5-1 8-4 8-9V7l-8-4Z"/><path d="m9 12 2 2 4-4"/></svg>',
        'Verification': '<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2Z"/></svg>',
        'Live logs': '<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 6h16M4 12h10M4 18h16"/><circle cx="18" cy="12" r="2"/></svg>',
    }
    for label, icon in icons.items():
        html = html.replace(f'>{label}</button>', f'>{icon}<span class="nav-text">{label}</span></button>')
    html = html.replace('<main class="main"><header class="top">', '<main class="main"><header class="top"><button id="sidebarToggle" class="sidebar-toggle" title="Toggle sidebar" aria-label="Toggle sidebar">☰</button>')
    html = html.replace('<div id="pageTitle" class="title">', '<div class="breadcrumbs"><span id="pageTitle" class="title">', 1)
    html = html.replace('</div><div id="build" class="muted"></div></div><div id="connectionBadge"', '</span></div><div id="build" class="muted"></div></div><div id="connectionBadge"', 1)
    html = html.replace('</div></header>', '</div><button id="themeToggle" class="theme-toggle" title="Toggle theme" aria-label="Toggle theme">☼</button></div></header>', 1)
    script = """
const theme=localStorage.getItem('codex-auth-beta-theme');if(theme==='light')document.documentElement.classList.add('theme-light');$('themeToggle').onclick=()=>{document.documentElement.classList.toggle('theme-light');localStorage.setItem('codex-auth-beta-theme',document.documentElement.classList.contains('theme-light')?'light':'dark')};$('sidebarToggle').onclick=()=>{$('app').classList.toggle('collapsed');localStorage.setItem('codex-auth-beta-sidebar',$('app').classList.contains('collapsed')?'collapsed':'expanded')};if(localStorage.getItem('codex-auth-beta-sidebar')==='collapsed')$('app').classList.add('collapsed');
"""
    html = html.replace('</script></body></html>', script + '</script></body></html>')
    return html


def dashboard_html() -> str:
    """Return the explicit shell with final contrast and mobile fixes."""

    html = _dashboard_html_raw()
    html = html.replace(
        ".nav button.active{background:#1f1f1f;color:var(--text);font-weight:600}",
        ".nav button.active{background:#1f1f1f;color:#fff;font-weight:600}",
    )
    html = html.replace(
        "</style></head>",
        ".nav button:focus-visible,.sidebar-toggle:focus-visible,.theme-toggle:focus-visible,.btn:focus-visible{outline:2px solid var(--blue);outline-offset:2px}.nav button,.sidebar-toggle,.theme-toggle,.btn{min-height:44px}</style></head>",
    )
    html = html.replace(
        "</script></body></html>",
        "const recovery=document.querySelector('#oauthPanel details');const legacy=document.querySelector('#account .legacy-account-recovery');if(recovery&&legacy)recovery.appendChild(legacy);</script></body></html>",
    )
    return html


def _dashboard_html_raw() -> str:
    """Return the explicit production-style beta dashboard shell."""

    return (r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Codex Auth Console · M365 Beta</title><style>
:root{color-scheme:dark;--bg:#000;--surface:#0a0a0a;--hover:#171717;--code:#050505;--line:#27272a;--strong:#3f3f46;--text:#fff;--muted:#a1a1aa;--tertiary:#52525b;--green:#10b981;--amber:#eab308;--red:#ef4444;--blue:#3b82f6;--sidebar:#050505;--blur:rgba(10,10,10,.86);--sans:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;--mono:"Geist Mono",ui-monospace,SFMono-Regular,Consolas,monospace}
:root.theme-light{color-scheme:light;--bg:#fafafa;--surface:#fff;--hover:#f4f4f5;--code:#f4f4f5;--line:#e4e4e7;--strong:#d4d4d8;--text:#18181b;--muted:#52525b;--tertiary:#a1a1aa;--sidebar:#fff;--blur:rgba(255,255,255,.88)}
*{box-sizing:border-box;margin:0;padding:0}body{min-height:100vh;background:var(--bg);background-image:radial-gradient(circle at center,rgba(127,127,127,.13) 1px,transparent 1px);background-size:24px 24px;color:var(--text);font:14px/1.45 var(--sans);-webkit-font-smoothing:antialiased}button,input,textarea{font:inherit}.hidden{display:none!important}.muted{color:var(--muted)}
.brand{display:flex;align-items:center;overflow:hidden}.brand-img{display:block;width:134px;height:40px;object-fit:contain;object-position:left center;content:url('/assets/logo-dark.svg')}.theme-light .brand-img{content:url('/assets/logo.svg')}
.login{min-height:100vh;display:grid;place-items:center;padding:24px}.login-card{width:min(450px,100%);padding:32px;border:1px solid var(--strong);border-radius:12px;background:var(--surface);box-shadow:0 28px 80px #0008}.login-card h1{font-size:26px;font-weight:600;letter-spacing:-.03em;margin:24px 0 8px}.login-card input{margin-top:22px}
input,textarea{width:100%;border:1px solid var(--line);border-radius:8px;background:var(--code);color:var(--text);padding:11px 12px;outline:none}input:focus,textarea:focus{border-color:var(--blue)}textarea{min-height:190px;resize:vertical}.btn{border:1px solid var(--strong);border-radius:7px;background:var(--surface);color:var(--text);padding:9px 13px;cursor:pointer;transition:.2s}.btn:hover{background:var(--hover);border-color:var(--muted)}.btn.primary{background:var(--text);color:var(--bg);border-color:var(--text);font-weight:600}.btn.blue{color:#fff;background:#2563eb;border-color:#3b82f6}.btn.danger{color:#fca5a5}.actions{display:flex;flex-wrap:wrap;gap:9px;margin-top:16px}.error{color:#fca5a5;min-height:20px;margin-top:10px}
.app{min-height:100vh;display:grid;grid-template-columns:240px minmax(0,1fr);transition:grid-template-columns .25s ease}.app.collapsed{grid-template-columns:72px}.sidebar{height:100vh;position:sticky;top:0;display:flex;flex-direction:column;background:var(--sidebar);border-right:1px solid var(--line);z-index:2}.sidebar-header{height:80px;padding:20px 24px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between}.sidebar.collapsed .sidebar-header{padding:20px 18px}.sidebar.collapsed .brand{width:36px}.sidebar.collapsed .brand-img{width:134px}.sidebar-toggle,.theme-toggle{display:flex;align-items:center;justify-content:center;border:0;background:transparent;color:var(--muted);cursor:pointer;border-radius:6px;padding:5px}.sidebar-toggle:hover,.theme-toggle:hover{background:var(--hover);color:var(--text)}.provider-subtitle{padding:16px 24px 2px;color:var(--muted);font-size:12px;line-height:1.4}.sidebar.collapsed .provider-subtitle{display:none}.nav{padding:12px;display:grid;gap:6px}.nav button{display:flex;align-items:center;gap:11px;width:100%;border:0;background:transparent;color:var(--muted);padding:10px 14px;border-radius:8px;text-align:left;cursor:pointer}.nav button:hover{background:rgba(127,127,127,.08);color:var(--text)}.nav button.active{background:#1f1f1f;color:var(--text);font-weight:600}.nav button svg{width:18px;height:18px;flex:0 0 18px}.sidebar.collapsed .nav button{justify-content:center;padding:10px}.sidebar.collapsed .nav-text{display:none}.side-bottom{margin-top:auto;padding:16px 12px}.sidebar.collapsed .side-bottom .btn{font-size:0;padding:10px}.sidebar.collapsed .side-bottom .btn:after{content:'↪';font-size:16px}
.main-content{min-width:0;display:flex;flex-direction:column;overflow:hidden}.topbar{height:72px;flex:0 0 72px;display:flex;align-items:center;justify-content:space-between;gap:24px;padding:0 32px;background:var(--blur);border-bottom:1px solid var(--line);backdrop-filter:blur(10px);z-index:1}.topbar-left{min-width:0}.breadcrumbs{font-size:14px;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.breadcrumbs span{color:var(--text);font-weight:500}.build{margin-top:4px;font:11px var(--mono);color:var(--tertiary);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.topbar-right{display:flex;align-items:center;gap:14px;flex:0 0 auto}.status-badge{display:inline-flex;align-items:center;gap:7px;padding:6px 12px;border-radius:999px;font-size:12px;font-weight:600;border:1px solid var(--line);color:var(--muted)}.status-badge.online{color:var(--green);border-color:rgba(16,185,129,.25);background:rgba(16,185,129,.1)}.status-badge.warning{color:var(--amber);border-color:rgba(234,179,8,.25);background:rgba(234,179,8,.1)}.dot{width:7px;height:7px;border-radius:50%;background:var(--amber)}.online .dot{background:var(--green)}
.view-container{flex:1;min-height:0;overflow-y:auto;overflow-x:hidden;padding:40px}.view{display:none;max-width:1500px;margin:0 auto}.view.active{display:block}.page-header{margin-bottom:32px}.page-header h1{font-size:24px;font-weight:600;letter-spacing:-.03em;margin-bottom:8px}.page-header p{color:var(--muted)}.bento-grid{display:grid;grid-template-columns:repeat(12,1fr);gap:16px;margin-bottom:32px}.card{min-width:0;background:var(--surface);border:1px solid var(--strong);border-radius:12px;padding:24px;transition:border-color .2s}.card:hover{border-color:var(--muted)}.col-4{grid-column:span 4}.col-6{grid-column:span 6}.col-8{grid-column:span 8}.col-12{grid-column:span 12}.card h2{font-size:18px;font-weight:600;margin-bottom:14px}.label,.card h3{color:var(--muted);font-size:12px;font-weight:500;text-transform:uppercase;letter-spacing:.05em;margin-bottom:12px}.metric{font-size:31px;font-weight:600;letter-spacing:-.03em}.sub-metric{margin-top:4px;color:var(--tertiary);font:13px var(--mono)}.kv{display:grid;grid-template-columns:160px 1fr;gap:9px 14px;margin-top:16px}.kv div:nth-child(odd){color:var(--muted)}.notice{border-left:3px solid var(--amber);border-radius:6px;background:rgba(234,179,8,.1);color:#facc15;padding:12px 14px;line-height:1.5}.notice.blue{border-color:var(--blue);background:rgba(59,130,246,.1);color:#93c5fd}.file{position:relative;overflow:hidden}.file input{position:absolute;inset:0;opacity:0;cursor:pointer}
table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:14px 16px;border-bottom:1px solid var(--line);vertical-align:top}th{color:var(--muted);font-size:12px;font-weight:500;text-transform:uppercase;letter-spacing:.05em;border-bottom-color:var(--strong)}td{font-size:13px}tr:last-child td{border-bottom:0}tr:hover td{background:var(--hover)}.state{font-size:12px;border:1px solid var(--line);padding:4px 8px;border-radius:5px;white-space:nowrap}.state.verified_live,.state.active{color:var(--green)}.state.blocked_by_upstream,.state.expiring_soon{color:var(--amber)}.state.unsupported,.state.re_import_required{color:var(--red)}
.logs{height:420px;overflow:auto;background:var(--code);border:1px solid var(--strong);border-radius:8px;padding:14px;font:12px/1.5 var(--mono);color:var(--muted)}.log{padding:7px 0;border-bottom:1px solid var(--line)}.log-empty{min-height:360px;display:grid;place-items:center;text-align:center;padding:32px;color:var(--muted)}.log-empty strong{display:block;color:var(--text);font-size:16px;margin-bottom:8px}.log-empty span{display:block;max-width:440px}.log-empty-icon{font-size:28px;color:var(--tertiary);margin-bottom:12px}
@media(max-width:1100px){.col-4{grid-column:span 6}}@media(max-width:800px){.col-4,.col-6,.col-8{grid-column:span 12}.kv{grid-template-columns:1fr}.kv div:nth-child(even){margin-bottom:7px}}@media(max-width:720px){.app{display:block}.sidebar{height:auto;position:static;border-right:0;border-bottom:1px solid var(--line)}.sidebar-header{height:68px}.provider-subtitle{display:none}.nav{grid-template-columns:repeat(3,1fr);padding:12px 10px}.nav button{justify-content:center;padding:9px 5px;font-size:12px}.nav button svg{width:16px;height:16px}.nav-text{white-space:nowrap}.side-bottom{padding:0 10px 12px}.topbar{height:60px;min-height:60px;padding:0 16px}.topbar-right .status-badge{display:none}.view-container{padding:24px 16px}.card{padding:18px}}
</style></head><body>
<section id="login" class="login"><div class="login-card"><div class="brand"><img class="brand-img" src="/assets/logo-dark.svg" alt="Codex Auth"></div><h1>M365 Beta Dashboard</h1><p class="muted">Operator access uses the beta admin key. It becomes a short-lived HttpOnly session and is never stored in browser storage.</p><input id="loginKey" type="password" autocomplete="current-password" placeholder="Admin key"><div class="actions"><button class="btn primary" id="loginButton">Sign in</button></div><p id="loginError" class="error"></p></div></section>
<section id="app" class="app hidden"><aside class="sidebar" id="sidebar"><div class="sidebar-header"><div class="brand"><img class="brand-img" src="/assets/logo-dark.svg" alt="Codex Auth"></div><button id="sidebarToggle" class="sidebar-toggle" title="Toggle sidebar" aria-label="Toggle sidebar"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M9 3v18"/></svg></button></div><div class="provider-subtitle">M365 bearer beta</div><nav class="nav" aria-label="Dashboard sections"><button data-view="overview" data-title="Overview" class="active" title="Overview"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></svg><span class="nav-text">Overview</span></button><button data-view="account" data-title="Account" title="Account"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg><span class="nav-text">Account</span></button><button data-view="models" data-title="Models" title="Models"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m12 2 10 5-10 5L2 7l10-5Z"/><path d="m2 12 10 5 10-5M2 17l10 5 10-5"/></svg><span class="nav-text">Models</span></button><button data-view="capabilities" data-title="Capabilities" title="Capabilities"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 3 4 7v5c0 5 3.5 8 8 9 4.5-1 8-4 8-9V7l-8-4Z"/><path d="m9 12 2 2 4-4"/></svg><span class="nav-text">Capabilities</span></button><button data-view="verification" data-title="Verification" title="Verification"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2Z"/></svg><span class="nav-text">Verification</span></button><button data-view="logs" data-title="Network Inspector" title="Network Inspector"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 6h16M4 12h10M4 18h16"/><circle cx="18" cy="12" r="2"/></svg><span class="nav-text">Live logs</span></button></nav><div class="side-bottom"><button id="logout" class="btn danger" style="width:100%">Sign out</button></div></aside>
<main class="main-content"><header class="topbar"><div class="topbar-left"><div class="breadcrumbs">Codex / <span id="pageTitle">Overview</span></div><div id="build" class="build"></div></div><div class="topbar-right"><div id="connectionBadge" class="status-badge warning"><span class="dot"></span><span>Loading</span></div><button id="themeToggle" class="theme-toggle" title="Toggle theme" aria-label="Toggle theme"><svg id="moonIcon" width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/></svg><svg id="sunIcon" width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="display:none"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M6.3 17.7l-1.4 1.4M19.1 4.9l-1.4 1.4"/></svg></button></div></header><div class="view-container">
<div id="overview" class="view active"><div class="page-header"><h1>Overview</h1><p>Cookie-free M365 bearer beta runtime, readiness, and evidence state.</p></div><div class="bento-grid"><div class="card col-4"><h3>Generation</h3><div id="generation" class="metric">—</div><div class="sub-metric">Current readiness</div></div><div class="card col-4"><h3>Credential</h3><div id="credentialState" class="metric">—</div><div class="sub-metric">OAuth lifecycle</div></div><div class="card col-4"><h3>Models</h3><div id="modelCount" class="metric">—</div><div class="sub-metric">Authenticated catalog</div></div><div class="card col-12"><h3>Persistence</h3><div id="persistence" class="metric">—</div><div class="sub-metric">Credential restart durability</div></div></div><div class="bento-grid"><div class="card col-6"><h2>Runtime</h2><div id="runtimeKv" class="kv"></div><div class="actions"><button class="btn blue" id="probe">Run safe connection test</button><button class="btn" id="refresh">Refresh credential</button></div><p id="actionStatus" class="muted" style="margin-top:12px"></p></div><div class="card col-6"><h2>Deployment readiness</h2><div id="readiness"></div></div></div></div>
<div id="account" class="view"><div class="page-header"><h1>Account & Session</h1><p>Microsoft sign-in, credential health, and safe runtime state.</p></div><div class="bento-grid"><div class="card col-8"><h2>Connect Microsoft 365</h2><p class="notice blue">Microsoft’s first-party client redirects browser authorization to Microsoft’s landing page. This dashboard can open sign-in, but cannot intercept its token response automatically.</p><div class="actions"><button class="btn blue" id="openMicrosoft">Open Microsoft 365 sign-in</button></div><ol class="muted" style="margin:16px 0 0 20px;line-height:1.8"><li>Sign in to Microsoft 365 in the opened tab.</li><li>Copy the successful OAuth response JSON from DevTools.</li><li>Paste it below or select the JSON file.</li></ol><textarea id="credentialJson" spellcheck="false" autocomplete="off" placeholder='{"token_type":"Bearer", ...}'></textarea><div class="actions"><label class="btn file">Choose JSON file<input id="credentialFile" type="file" accept="application/json,.json"></label><button class="btn primary" id="importCredential">Import / Replace</button></div><p id="importStatus" class="muted" style="margin-top:12px"></p></div><div class="card col-4"><h2>Credential health</h2><div id="credentialKv" class="kv"></div><p class="notice" style="margin-top:18px">The dashboard never returns access or refresh tokens. Runtime imports survive restart only with encrypted external Postgres.</p></div></div></div>
<div id="models" class="view"><div class="page-header"><h1>Available Models</h1><p>Account-visible M365 models with source and reasoning metadata.</p></div><div class="bento-grid"><div class="card col-12"><div class="section-head"><h2>Upstream model catalog</h2><span class="muted">Catalog source is shown per model</span></div><div style="overflow:auto"><table><thead><tr><th>Model</th><th>Name</th><th>Source</th><th>Reasoning</th></tr></thead><tbody id="modelsBody"></tbody></table></div></div></div></div>
<div id="capabilities" class="view"><div class="page-header"><h1>Capability Evidence</h1><p>Evidence-linked capability states; unsupported behavior is never promoted.</p></div><div class="bento-grid"><div class="card col-12"><div class="section-head"><h2>Proxy capability matrix</h2><span class="muted">No mock-only promotion</span></div><div style="overflow:auto"><table><thead><tr><th>Feature</th><th>State</th><th>Comparison</th><th>Evidence</th></tr></thead><tbody id="capabilitiesBody"></tbody></table></div></div></div></div>
<div id="verification" class="view"><div class="page-header"><h1>Verification & Metrics</h1><p>Commit-bound verification and redacted runtime telemetry.</p></div><div class="bento-grid"><div class="card col-6"><h2>Commit-bound verification</h2><div id="verificationKv" class="kv"></div></div><div class="card col-6"><h2>Metrics</h2><div id="metricsKv" class="kv"></div></div></div></div>
<div id="logs" class="view"><div class="page-header"><h1>Network Inspector</h1><p>Live redacted runtime events and connection phases.</p></div><div class="bento-grid"><div class="card col-12" style="padding:0;overflow:hidden"><div id="logBox" class="logs"><div id="logEmpty" class="log-empty"><div><div class="log-empty-icon">⌁</div><strong>No runtime events yet</strong><span>Telemetry will appear here after a dashboard action or generation request. Prompts, responses, tokens, URLs, and identities are excluded.</span></div></div></div></div></div></div>
</div></main></section>
<script>
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let state=null,events=null;
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});let data={};try{data=await response.json()}catch{}if(response.status===401){showLogin();throw new Error('Dashboard session expired')}if(!response.ok)throw new Error(data.error||data.detail||'Request failed');return data}
function showLogin(){$('app').classList.add('hidden');$('login').classList.remove('hidden');if(events){events.close();events=null}}
function showApp(){$('login').classList.add('hidden');$('app').classList.remove('hidden')}
function kv(target,items){target.innerHTML=Object.entries(items).map(([k,v])=>`<div>${esc(k.replaceAll('_',' '))}</div><div>${esc(v??'Unavailable')}</div>`).join('')}
function badge(ok,text){$('connectionBadge').className='status-badge '+(ok?'online':'warning');$('connectionBadge').innerHTML=`<span class="dot"></span><span>${esc(text)}</span>`}
function setView(button){document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===button.dataset.view));$('pageTitle').textContent=button.dataset.title}
function applyTheme(){const light=document.documentElement.classList.contains('theme-light');$('moonIcon').style.display=light?'none':'block';$('sunIcon').style.display=light?'block':'none'}
async function load(){state=await api('/dashboard/api/overview');showApp();const c=state.credential||{},p=c.credential_persistence||{},models=state.models?.data||[],ready=state.readiness||{};$('generation').textContent=c.generation_ready?'Ready':'Blocked';$('credentialState').textContent=c.state||'Unknown';$('modelCount').textContent=models.length;$('persistence').textContent=p.restart_durable?'Durable':'Ephemeral';$('build').textContent=`Commit ${state.build?.render_commit||'unknown'} · contract ${state.build?.verification_contract||'unknown'}`;badge(c.generation_ready,c.generation_ready?'Connected':'Action required');kv($('runtimeKv'),{cookie_count:c.cookie_count,generation_ready:c.generation_ready,refresh_ready:c.refresh_ready,last_refresh_outcome:c.last_refresh_outcome,recovery_action:c.recovery_action});$('readiness').innerHTML=`<p class="${ready.ready?'':'notice'}">${ready.ready?'Ready for hosted generation':esc((ready.warnings||[]).join(' · ')||'Not ready')}</p>`;kv($('credentialKv'),{state:c.state,access_expires_in_seconds:c.access_expires_in_seconds,refresh_available:c.refresh_available,refresh_capture_state:c.refresh_capture_state,persistence_source:p.source,restart_durable:p.restart_durable});$('modelsBody').innerHTML=models.map(m=>`<tr><td>${esc(m.id)}</td><td>${esc(m.display_name||m.name||m.id)}</td><td>${esc(m.source||state.models?.source||'unknown')}</td><td>${esc(m.reasoning||m.metadata?.reasoning||'provider-defined')}</td></tr>`).join('')||'<tr><td colspan="4">No models reported</td></tr>';const features=state.capabilities?.features||[];$('capabilitiesBody').innerHTML=features.map(f=>`<tr><td>${esc(f.feature)}</td><td><span class="state ${esc(f.state)}">${esc(f.state)}</span></td><td>${esc(f.comparison)}</td><td>${esc(f.evidence_id)}</td></tr>`).join('');const v=state.verification?.verification||{};kv($('verificationKv'),{state:v.state,tested_commit:v.tested_commit,digest:v.digest,completed_at:v.completed_at?new Date(v.completed_at*1000).toLocaleString():null});const m=state.metrics||{};kv($('metricsKv'),{events:m.event_count,completed_generations:m.completed_generations,success_rate:m.success_rate,p50_ms:m.latency_ms?.p50,p95_ms:m.latency_ms?.p95,last_event_at:m.last_event_at?new Date(m.last_event_at*1000).toLocaleString():null});startLogs()}
function startLogs(){if(events)events.close();events=new EventSource('/dashboard/api/logs/stream');events.addEventListener('telemetry',event=>{let item={};try{item=JSON.parse(event.data)}catch{};$('logEmpty')?.remove();const row=document.createElement('div');row.className='log';row.textContent=`${new Date((item.timestamp||0)*1000).toLocaleTimeString()}  ${item.event||'event'}  ${item.status||''}  ${item.model||''}  ${item.error_phase||''}`;$('logBox').appendChild(row);$('logBox').scrollTop=$('logBox').scrollHeight;while($('logBox').children.length>200)$('logBox').firstChild.remove()})}
$('loginButton').onclick=async()=>{const key=$('loginKey').value;$('loginError').textContent='';try{await api('/dashboard/login',{method:'POST',body:JSON.stringify({admin_key:key})});$('loginKey').value='';await load()}catch(error){$('loginKey').value='';$('loginError').textContent=error.message}};$('logout').onclick=async()=>{await api('/dashboard/logout',{method:'POST'}).catch(()=>{});showLogin()};document.querySelectorAll('.nav button').forEach(button=>button.onclick=()=>setView(button));
const themeKey='codex-auth-beta-theme';if(localStorage.getItem(themeKey)==='light')document.documentElement.classList.add('theme-light');applyTheme();$('themeToggle').onclick=()=>{document.documentElement.classList.toggle('theme-light');localStorage.setItem(themeKey,document.documentElement.classList.contains('theme-light')?'light':'dark');applyTheme()};const sidebarKey='codex-auth-beta-sidebar-v2';if(localStorage.getItem(sidebarKey)==='collapsed')$('app').classList.add('collapsed');$('sidebarToggle').onclick=()=>{$('app').classList.toggle('collapsed');localStorage.setItem(sidebarKey,$('app').classList.contains('collapsed')?'collapsed':'expanded')};
$('openMicrosoft').onclick=()=>window.open('https://m365.cloud.microsoft/chat?auth=2','_blank','noopener,noreferrer');$('credentialFile').onchange=async event=>{const file=event.target.files[0];if(file)$('credentialJson').value=await file.text();event.target.value=''};$('importCredential').onclick=async()=>{let credential;try{credential=JSON.parse($('credentialJson').value)}catch{$('importStatus').textContent='Select or paste a valid OAuth JSON object.';return}$('importStatus').textContent='Importing…';try{const result=await api('/dashboard/api/credentials/import',{method:'POST',body:JSON.stringify({credential})});$('importStatus').textContent=`Imported: ${result.credential.state}`;await load()}catch(error){$('importStatus').textContent=error.message}finally{$('credentialJson').value='';credential=null}};$('refresh').onclick=async()=>{$('actionStatus').textContent='Refreshing…';try{const result=await api('/dashboard/api/refresh',{method:'POST'});$('actionStatus').textContent=`Refresh: ${result.credential.state}`;await load()}catch(error){$('actionStatus').textContent=error.message}};$('probe').onclick=async()=>{$('actionStatus').textContent='Running zero-cookie marker probe…';try{const result=await api('/dashboard/api/probe',{method:'POST'});$('actionStatus').textContent=`${result.state}; ${result.latency_ms} ms; marker ${result.marker_observed?'verified':'missing'}`;await load()}catch(error){$('actionStatus').textContent=error.message}};fetch('/dashboard/api/overview').then(r=>{if(r.ok)return load();showLogin()}).catch(showLogin);
const pasteCredential=document.createElement('button');pasteCredential.type='button';pasteCredential.className='btn';pasteCredential.id='pasteCredential';pasteCredential.textContent='Paste OAuth JSON';pasteCredential.onclick=async()=>{try{const value=await navigator.clipboard.readText();if(!value)throw new Error('Clipboard is empty');$('credentialJson').value=value;$('importStatus').textContent='OAuth JSON captured from clipboard. Review, then import.'}catch(error){$('importStatus').textContent='Clipboard access was blocked; use the file picker or paste manually.'}};const fileLabel=$('credentialFile')?.parentElement;if(fileLabel)fileLabel.parentElement.insertBefore(pasteCredential,fileLabel.nextSibling);
const accountView=$('account');if(accountView&&!$('oauthPanel')){const legacy=accountView.querySelector('.bento-grid');if(legacy)legacy.classList.add('legacy-account-recovery');const panel=document.createElement('section');panel.id='oauthPanel';panel.className='card oauth-panel';panel.innerHTML='<h2>Connect Microsoft 365</h2><p id="oauthNotice" class="notice blue">Use hosted Microsoft sign-in when an operator Entra app is configured. The callback returns here automatically.</p><p id="durabilityWarning" class="notice" hidden>Restart-safe credential storage is required before import, refresh, probes, image, or file generation. Configure CODEX_AUTH_M365_BETA_DATABASE_URL, CODEX_AUTH_M365_BETA_CREDENTIAL_KEY, and CODEX_AUTH_M365_BETA_REQUIRE_DURABLE=1 on the beta service.</p><div class="actions account-actions"><button class="btn blue" id="startOAuth">Continue with Microsoft</button></div><p id="oauthStatus" class="muted" aria-live="polite"></p><details class="account-recovery"><summary>Advanced recovery</summary><p class="muted">Use OAuth JSON import only when hosted authorization is unavailable.</p></details>';accountView.insertBefore(panel,legacy||accountView.firstChild);$('startOAuth').onclick=async()=>{const status=$('oauthStatus');status.textContent='Starting Microsoft authorization…';try{const result=await api('/dashboard/api/oauth/start',{method:'POST'});window.location.assign(result.authorization_url)}catch(error){status.textContent=error.message}};api('/dashboard/api/oauth/status').then(result=>{if(!result.automatic_login){$('oauthNotice').textContent='Hosted authorization is not configured yet. Use Advanced recovery below.';$('startOAuth').disabled=true}}).catch(()=>{})}};setTimeout(()=>{const c=state?.credential||{},p=c.credential_persistence||{};const durable=Boolean(p.restart_durable&&p.source==='encrypted_external_postgres');['importCredential','refresh','probe','startOAuth'].forEach(id=>{const button=$(id);if(button)button.disabled=!durable});const warning=$('durabilityWarning');if(warning)warning.hidden=durable},1200)</script></body></html>'''.replace('.sidebar.collapsed', '.app.collapsed'))
